name: LFS-warning

on:
  pull_request:
    types: [assigned, opened, edited, reopened, synchronize, ready_for_review]
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  lfs-warning:

    name: LFS Warning
    runs-on: ubuntu-latest

    steps:
      - name: Get Repo Code
        id: get_repo_code
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: '20'

      - name: LFS Warning
        id: lfs_warning
        uses: ./
        with:
          filesizelimit: 10MB
          exclusionPatterns: |
            **/*.png
